"""baseline schema — mirrors docs/04_DATABASE_SCHEMA.sql

This is a hand-authored baseline rather than an autogenerated diff: Phase 1 already
fully designed and reviewed the schema, so this migration applies that reviewed DDL
directly instead of re-deriving it from ORM models that don't exist yet for most of
these tables (only User, Project, Repository have model classes so far -- see
app/db/models/). Migrations written after this one, once more models exist, should
use `alembic revision --autogenerate`.

Revision ID: 0001
Revises:
Create Date: 2026-08-18

"""
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TYPE user_role AS ENUM ('admin', 'developer', 'viewer');

CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email           VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    full_name       VARCHAR(255),
    role            user_role NOT NULL DEFAULT 'developer',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE projects (
    id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name       VARCHAR(255) NOT NULL,
    owner_id   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TYPE indexing_status AS ENUM
    ('pending', 'cloning', 'parsing', 'analyzing', 'embedding', 'ready', 'failed');

CREATE TABLE repositories (
    id                       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id               UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    remote_url               VARCHAR(1024) NOT NULL,
    default_branch           VARCHAR(255) DEFAULT 'main',
    local_path                VARCHAR(1024),
    primary_language         VARCHAR(64),
    status                   indexing_status NOT NULL DEFAULT 'pending',
    last_indexed_commit_hash VARCHAR(64),
    last_indexed_at          TIMESTAMPTZ,
    stats                    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_repositories_project ON repositories(project_id);
CREATE INDEX idx_repositories_status  ON repositories(status);

CREATE TABLE directories (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    parent_id     UUID REFERENCES directories(id) ON DELETE CASCADE,
    path          VARCHAR(2048) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    UNIQUE (repository_id, path)
);
CREATE INDEX idx_directories_repo   ON directories(repository_id);
CREATE INDEX idx_directories_parent ON directories(parent_id);

CREATE TABLE files (
    id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id  UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    directory_id   UUID REFERENCES directories(id) ON DELETE CASCADE,
    path           VARCHAR(2048) NOT NULL,
    filename       VARCHAR(255) NOT NULL,
    extension      VARCHAR(32),
    language       VARCHAR(64),
    content_hash   CHAR(64) NOT NULL,
    loc            INTEGER NOT NULL DEFAULT 0,
    size_bytes     INTEGER NOT NULL DEFAULT 0,
    is_test_file   BOOLEAN NOT NULL DEFAULT FALSE,
    is_generated   BOOLEAN NOT NULL DEFAULT FALSE,
    last_parsed_at TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (repository_id, path)
);
CREATE INDEX idx_files_repo     ON files(repository_id);
CREATE INDEX idx_files_language ON files(language);
CREATE INDEX idx_files_hash     ON files(content_hash);

CREATE TABLE classes (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    file_id         UUID NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    qualified_name  VARCHAR(1024),
    docstring       TEXT,
    start_line      INTEGER NOT NULL,
    end_line        INTEGER NOT NULL,
    parent_class_id UUID REFERENCES classes(id),
    is_abstract     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_classes_file       ON classes(file_id);
CREATE INDEX idx_classes_name_trgm  ON classes USING gin (name gin_trgm_ops);

CREATE TABLE methods (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    class_id    UUID NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    signature   TEXT,
    return_type VARCHAR(255),
    visibility  VARCHAR(32) NOT NULL DEFAULT 'public',
    is_static   BOOLEAN NOT NULL DEFAULT FALSE,
    is_async    BOOLEAN NOT NULL DEFAULT FALSE,
    docstring   TEXT,
    start_line  INTEGER NOT NULL,
    end_line    INTEGER NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_methods_class      ON methods(class_id);
CREATE INDEX idx_methods_name_trgm  ON methods USING gin (name gin_trgm_ops);

CREATE TABLE functions (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    file_id          UUID NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    name             VARCHAR(255) NOT NULL,
    qualified_name   VARCHAR(1024),
    signature        TEXT,
    return_type      VARCHAR(255),
    parameters       JSONB NOT NULL DEFAULT '[]'::jsonb,
    docstring        TEXT,
    is_async         BOOLEAN NOT NULL DEFAULT FALSE,
    is_exported      BOOLEAN NOT NULL DEFAULT FALSE,
    start_line       INTEGER NOT NULL,
    end_line         INTEGER NOT NULL,
    complexity_score INTEGER,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_functions_file       ON functions(file_id);
CREATE INDEX idx_functions_name_trgm  ON functions USING gin (name gin_trgm_ops);

CREATE TABLE imports (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    file_id          UUID NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    imported_symbol  VARCHAR(512) NOT NULL,
    source_module    VARCHAR(1024) NOT NULL,
    resolved_file_id UUID REFERENCES files(id) ON DELETE SET NULL,
    is_external      BOOLEAN NOT NULL DEFAULT FALSE,
    alias            VARCHAR(255),
    line_number      INTEGER
);
CREATE INDEX idx_imports_file     ON imports(file_id);
CREATE INDEX idx_imports_resolved ON imports(resolved_file_id);

CREATE TABLE exports (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    file_id     UUID NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    symbol_name VARCHAR(512) NOT NULL,
    symbol_type VARCHAR(64),
    line_number INTEGER
);
CREATE INDEX idx_exports_file ON exports(file_id);

CREATE TABLE dependencies (
    id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id     UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    package_name      VARCHAR(255) NOT NULL,
    version           VARCHAR(64),
    ecosystem         VARCHAR(64),
    is_dev_dependency BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_dependencies_repo ON dependencies(repository_id);

CREATE TABLE call_graph (
    id                 UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id      UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    caller_function_id UUID REFERENCES functions(id) ON DELETE CASCADE,
    caller_method_id   UUID REFERENCES methods(id) ON DELETE CASCADE,
    callee_function_id UUID REFERENCES functions(id) ON DELETE CASCADE,
    callee_method_id   UUID REFERENCES methods(id) ON DELETE CASCADE,
    callee_raw_name    VARCHAR(512),
    call_line          INTEGER,
    CONSTRAINT caller_present CHECK (caller_function_id IS NOT NULL OR caller_method_id IS NOT NULL),
    CONSTRAINT callee_present CHECK (callee_function_id IS NOT NULL OR callee_method_id IS NOT NULL OR callee_raw_name IS NOT NULL)
);
CREATE INDEX idx_callgraph_repo       ON call_graph(repository_id);
CREATE INDEX idx_callgraph_caller_fn  ON call_graph(caller_function_id);
CREATE INDEX idx_callgraph_caller_mth ON call_graph(caller_method_id);
CREATE INDEX idx_callgraph_callee_fn  ON call_graph(callee_function_id);
CREATE INDEX idx_callgraph_callee_mth ON call_graph(callee_method_id);

CREATE TABLE api_routes (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id       UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    file_id             UUID REFERENCES files(id) ON DELETE CASCADE,
    handler_function_id UUID REFERENCES functions(id) ON DELETE SET NULL,
    handler_method_id   UUID REFERENCES methods(id) ON DELETE SET NULL,
    http_method         VARCHAR(16) NOT NULL,
    path                VARCHAR(1024) NOT NULL,
    middleware          JSONB NOT NULL DEFAULT '[]'::jsonb,
    requires_auth       BOOLEAN NOT NULL DEFAULT FALSE,
    line_number         INTEGER
);
CREATE INDEX idx_apiroutes_repo ON api_routes(repository_id);
CREATE INDEX idx_apiroutes_path ON api_routes(path);

CREATE TABLE database_queries (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    file_id      UUID NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    function_id  UUID REFERENCES functions(id) ON DELETE SET NULL,
    method_id    UUID REFERENCES methods(id) ON DELETE SET NULL,
    query_type   VARCHAR(32),
    raw_snippet  TEXT,
    target_table VARCHAR(255),
    line_number  INTEGER
);
CREATE INDEX idx_dbqueries_file  ON database_queries(file_id);
CREATE INDEX idx_dbqueries_table ON database_queries(target_table);

CREATE TABLE commits (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    commit_hash   CHAR(40) NOT NULL,
    author_name   VARCHAR(255),
    author_email  VARCHAR(255),
    committed_at  TIMESTAMPTZ,
    message       TEXT,
    files_changed JSONB NOT NULL DEFAULT '[]'::jsonb,
    diff_summary  TEXT,
    branch        VARCHAR(255),
    UNIQUE (repository_id, commit_hash)
);
CREATE INDEX idx_commits_repo ON commits(repository_id);
CREATE INDEX idx_commits_date ON commits(committed_at);

CREATE TABLE issues (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    external_id   VARCHAR(64),
    title         VARCHAR(1024),
    body          TEXT,
    state         VARCHAR(32),
    created_at    TIMESTAMPTZ
);
CREATE INDEX idx_issues_repo ON issues(repository_id);

CREATE TABLE knowledge_nodes (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    node_type     VARCHAR(64) NOT NULL,
    ref_id        UUID,
    label         VARCHAR(512) NOT NULL,
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX idx_nodes_repo ON knowledge_nodes(repository_id);
CREATE INDEX idx_nodes_type ON knowledge_nodes(node_type);
CREATE INDEX idx_nodes_ref  ON knowledge_nodes(ref_id);

CREATE TABLE knowledge_edges (
    id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id  UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    source_node_id UUID NOT NULL REFERENCES knowledge_nodes(id) ON DELETE CASCADE,
    target_node_id UUID NOT NULL REFERENCES knowledge_nodes(id) ON DELETE CASCADE,
    edge_type      VARCHAR(64) NOT NULL,
    weight         REAL NOT NULL DEFAULT 1.0,
    metadata       JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX idx_edges_repo   ON knowledge_edges(repository_id);
CREATE INDEX idx_edges_source ON knowledge_edges(source_node_id);
CREATE INDEX idx_edges_target ON knowledge_edges(target_node_id);
CREATE INDEX idx_edges_type   ON knowledge_edges(edge_type);

CREATE TABLE embeddings (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    source_type   VARCHAR(64) NOT NULL,
    source_id     UUID NOT NULL,
    chunk_text    TEXT NOT NULL,
    chunk_index   INTEGER NOT NULL DEFAULT 0,
    embedding     vector(1536) NOT NULL,
    model_name    VARCHAR(128) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_embeddings_repo   ON embeddings(repository_id);
CREATE INDEX idx_embeddings_source ON embeddings(source_type, source_id);
CREATE INDEX idx_embeddings_vector ON embeddings USING hnsw (embedding vector_cosine_ops);

CREATE TABLE documentation (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    file_id       UUID REFERENCES files(id) ON DELETE CASCADE,
    doc_type      VARCHAR(32),
    title         VARCHAR(512),
    content       TEXT NOT NULL,
    section_path  VARCHAR(512)
);
CREATE INDEX idx_documentation_repo ON documentation(repository_id);

CREATE TABLE chat_sessions (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id UUID NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title         VARCHAR(512),
    is_pinned     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_chatsessions_repo ON chat_sessions(repository_id);
CREATE INDEX idx_chatsessions_user ON chat_sessions(user_id);

CREATE TABLE chat_history (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id       UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role             VARCHAR(16) NOT NULL,
    content          TEXT NOT NULL,
    sources          JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence_score REAL,
    is_saved         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_chathistory_session ON chat_history(session_id);
"""

# Reverse-dependency order so FK constraints never block a DROP.
DROP_TABLES = [
    "chat_history", "chat_sessions", "documentation", "embeddings",
    "knowledge_edges", "knowledge_nodes", "issues", "commits",
    "database_queries", "api_routes", "call_graph", "dependencies",
    "exports", "imports", "functions", "methods", "classes",
    "files", "directories", "repositories", "projects", "users",
]


def upgrade() -> None:
    op.execute(SCHEMA_SQL)


def downgrade() -> None:
    for table in DROP_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    op.execute("DROP TYPE IF EXISTS indexing_status")
    op.execute("DROP TYPE IF EXISTS user_role")
